# Generated by Django 2.2 on 2020-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='%s/letter/'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='naid',
            field=models.FileField(blank=True, null=True, upload_to='%s/naid/'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='birth',
            field=models.FileField(blank=True, null=True, upload_to='%s/birth/'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='contact1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='contact2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
