# Generated by Django 2.2 on 2020-01-10 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship', '0002_auto_20200110_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
